-- Migration: ensure all timestamp columns use TIMESTAMP WITH TIME ZONE (UTC)
-- Generated by Codex on 2025-09-26

BEGIN;

-- quotes
ALTER TABLE quotes
    ALTER COLUMN created_at TYPE TIMESTAMPTZ USING created_at AT TIME ZONE 'UTC',
    ALTER COLUMN updated_at TYPE TIMESTAMPTZ USING updated_at AT TIME ZONE 'UTC';

-- estimates
ALTER TABLE estimates
    ALTER COLUMN created_at TYPE TIMESTAMPTZ USING created_at AT TIME ZONE 'UTC';

-- breaker_settings
ALTER TABLE breaker_settings
    ALTER COLUMN updated_at TYPE TIMESTAMPTZ USING updated_at AT TIME ZONE 'UTC';

-- knowledge_packs
ALTER TABLE knowledge_packs
    ALTER COLUMN updated_at TYPE TIMESTAMPTZ USING updated_at AT TIME ZONE 'UTC';

-- policy_agreements
ALTER TABLE policy_agreements
    ALTER COLUMN signed_at TYPE TIMESTAMPTZ USING signed_at AT TIME ZONE 'UTC';

-- approval_requests
ALTER TABLE approval_requests
    ALTER COLUMN due_at TYPE TIMESTAMPTZ USING due_at AT TIME ZONE 'UTC',
    ALTER COLUMN created_at TYPE TIMESTAMPTZ USING created_at AT TIME ZONE 'UTC';

-- agent_queue_cards
ALTER TABLE agent_queue_cards
    ALTER COLUMN updated_at TYPE TIMESTAMPTZ USING updated_at AT TIME ZONE 'UTC';

-- evidence_bundles
ALTER TABLE evidence_bundles
    ALTER COLUMN created_at TYPE TIMESTAMPTZ USING created_at AT TIME ZONE 'UTC';

-- file_analysis_jobs
ALTER TABLE file_analysis_jobs
    ALTER COLUMN created_at TYPE TIMESTAMPTZ USING created_at AT TIME ZONE 'UTC';

-- file_guard_audits
ALTER TABLE file_guard_audits
    ALTER COLUMN timestamp TYPE TIMESTAMPTZ USING timestamp AT TIME ZONE 'UTC';

-- mail_sessions
ALTER TABLE mail_sessions
    ALTER COLUMN created_at TYPE TIMESTAMPTZ USING created_at AT TIME ZONE 'UTC';

-- mail_drafts
ALTER TABLE mail_drafts
    ALTER COLUMN created_at TYPE TIMESTAMPTZ USING created_at AT TIME ZONE 'UTC';

-- quote_revisions
ALTER TABLE quote_revisions
    ALTER COLUMN created_at TYPE TIMESTAMPTZ USING created_at AT TIME ZONE 'UTC';

COMMIT;
