-- Migration: ensure TIMESTAMPTZ
BEGIN;
ALTER TABLE IF EXISTS quotes
    ALTER COLUMN created_at TYPE TIMESTAMPTZ USING created_at AT TIME ZONE 'UTC',
    ALTER COLUMN updated_at TYPE TIMESTAMPTZ USING updated_at AT TIME ZONE 'UTC';
COMMIT;
