name: SLO Collector

on:
  schedule:
    - cron: "0 * * * *"   # 매시간
  workflow_dispatch: {}

jobs:
  collect:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Ensure jq (optional)
        shell: bash
        run: |
          set -euo pipefail
          if ! command -v jq >/dev/null 2>&1; then
            sudo apt-get update && sudo apt-get install -y jq
          fi

      - name: Prepare SLO folder
        shell: bash
        run: |
          set -euo pipefail
          mkdir -p .slo
          # 샘플 보고서가 없으면 생성(운영에 맞게 다른 스텝에서 덮어써도 됨)
          if [ ! -f ops/slo_report.json ]; then
            mkdir -p ops
            echo '{"status":"ok","ts":"'"$(date -u +%Y-%m-%dT%H:%M:%SZ)"'"}' > ops/slo_report.json
          fi
          # 스냅샷 생성
          cat > .slo/SLO_SNAPSHOT.md <<'EOF'
          # SLO Snapshot
          source: slo_collector
          ts: $(date -u +"%Y-%m-%dT%H:%M:%SZ")
          status: $(jq -r '.status' ops/slo_report.json 2>/dev/null || echo unknown)
          EOF

      - name: Commit & Push SLO snapshot
        shell: bash
        run: |
          set -euo pipefail
          git config user.name "KIS Bot"
          git config user.email "bot@kis.local"

          git add ops/slo_report.json .slo/SLO_SNAPSHOT.md 2>/dev/null || true

          if ! git diff --staged --quiet; then
            TIMESTAMP="$(date -u '+%Y-%m-%d %H:%M:%S')"
            if command -v jq >/dev/null 2>&1; then
              SLO_STATUS="$(jq -r '.status' ops/slo_report.json 2>/dev/null || echo unknown)"
            else
              SLO_STATUS="unknown"
            fi
            git commit -m "chore(slo): update snapshot (${TIMESTAMP}, status=${SLO_STATUS})" || echo "No changes to commit"
            git push
          else
            echo "No staged changes"
          fi